from __future__ import annotations

from dataclasses import dataclass, field
import math
import random
from typing import Callable, Dict, List, Sequence

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

from ...contracts import MetricDict, TaskDefinition
from ...trainers.utils import move_to_device
from ..CL.base import last_linear_module
from ..CL.iCaRL import Exemplar, _stored_exemplar
from .base import RobustReplayLearner


@dataclass
class AFLCRAERLearner(RobustReplayLearner):
    """Anti-Forgettable Logit Calibration with Robustness-Aware Replay.

    This is the ER+AT instantiation in Mi et al. (ICCV 2025): AFLC applies
    class-frequency and task-aware margins, future prior initializes unseen
    heads, and RAER keeps samples with fewer than ``rho`` successful PGD
    steps before random memory selection.
    """

    calibration_alpha: float = 3.5
    raer_threshold: int = 5
    future_prior: bool = True
    adaptive_eval_attack: bool = False
    class_counts: Dict[int, int] = field(default_factory=dict, init=False)
    _raer_candidates: Dict[int, List[tuple[Exemplar | int, int]]] = field(
        default_factory=dict, init=False, repr=False
    )
    _raer_source_dataset: Dataset | None = field(
        default=None, init=False, repr=False
    )

    def __post_init__(self) -> None:
        super().__post_init__()
        if float(self.calibration_alpha) < 0.0:
            raise ValueError("calibration_alpha must be non-negative.")
        if not 0 <= int(self.raer_threshold) <= int(self.attack_config.steps) + 1:
            raise ValueError("raer_threshold must be between 0 and PGD steps + 1.")

    def _calibration_values(
        self,
        class_ids: Sequence[int],
        *,
        device: torch.device,
        dtype: torch.dtype,
    ) -> torch.Tensor:
        seen = list(self.seen_classes)
        total = sum(max(0, int(self.class_counts.get(class_id, 0))) for class_id in seen)
        total = max(1, total)
        seen_values: Dict[int, float] = {}
        for class_id in seen:
            count = max(1, int(self.class_counts.get(class_id, 0)))
            value = -math.log(float(count) / float(total))
            # Eq. (9): alpha_i is applied to current classes.  Subtracting it
            # widens v_p > v_c and therefore suppresses past-class negative
            # gradients generated by current adversarial examples.
            if class_id in self.new_classes:
                value -= float(self.calibration_alpha)
            seen_values[class_id] = value
        future_value = (
            sum(seen_values.values()) / max(1, len(seen_values))
            if self.future_prior
            else 0.0
        )
        values = [seen_values.get(int(class_id), future_value) for class_id in class_ids]
        return torch.tensor(values, device=device, dtype=dtype)

    def calibrate_logits(
        self, logits: torch.Tensor, class_ids: Sequence[int] | None = None
    ) -> torch.Tensor:
        selected = list(range(logits.shape[1])) if class_ids is None else list(class_ids)
        if len(selected) != logits.shape[1]:
            raise ValueError("class_ids must identify every column of logits.")
        values = self._calibration_values(
            selected, device=logits.device, dtype=logits.dtype
        )
        return logits - values.unsqueeze(0)

    def calibration_margin(self) -> float:
        """Return the mean paper margin ``v_p - v_c`` for diagnostics."""

        if not self.old_classes or not self.new_classes:
            return 0.0
        class_ids = [*self.old_classes, *self.new_classes]
        values = self._calibration_values(
            class_ids, device=torch.device("cpu"), dtype=torch.float64
        )
        old_count = len(self.old_classes)
        return float(
            (
                values[:old_count].mean()
                - values[old_count:].mean()
            ).item()
        )

    def evaluation_attack_calibrator(
        self, class_ids: Sequence[int]
    ) -> Callable[[torch.Tensor], torch.Tensor] | None:
        if not self.adaptive_eval_attack:
            return None
        return lambda logits: self.calibrate_logits(logits, class_ids)

    def _refresh_class_counts(self, dataloader: DataLoader) -> None:
        for class_id in self.old_classes:
            self.class_counts[class_id] = len(self.exemplar_sets.get(class_id, []))
        current_counts = {class_id: 0 for class_id in self.new_classes}
        for index in range(len(dataloader.dataset)):
            item = dataloader.dataset[index]
            target = int(item[1])
            if target in current_counts:
                current_counts[target] += 1
        self.class_counts.update(current_counts)

    def observe(
        self,
        inputs: torch.Tensor,
        targets: torch.Tensor,
        task_id: str,
        *,
        source_indices: Sequence[int] | torch.Tensor | None = None,
        source_dataset: Dataset | None = None,
    ) -> MetricDict:
        del task_id
        stream_count = int(targets.shape[0])
        if source_indices is not None and len(source_indices) != stream_count:
            raise ValueError("source_indices must identify every stream sample.")
        if source_indices is not None and source_dataset is None:
            raise ValueError("source_dataset is required when source_indices are provided.")
        if source_indices is not None:
            if (
                self._raer_source_dataset is not None
                and self._raer_source_dataset is not source_dataset
            ):
                raise ValueError("RAER source dataset changed within one task.")
            self._raer_source_dataset = source_dataset
        replay = self.sample_memory(self.replay_count(stream_count))
        if replay is not None:
            memory_inputs, memory_targets, _indices = replay
            clean = torch.cat((inputs, memory_inputs), dim=0)
            labels = torch.cat((targets, memory_targets), dim=0)
        else:
            clean, labels = inputs, targets

        all_classes = list(range(int(last_linear_module(self.model).out_features)))
        adversarial, difficulty = self.generate_adversarial(
            clean,
            labels,
            class_ids=all_classes,
            return_difficulty=True,
        )
        for index in range(stream_count):
            class_id = int(labels[index].item())
            if source_indices is None:
                candidate: Exemplar | int = (
                    clean[index].detach().cpu().clone(),
                    class_id,
                )
            else:
                # Materializing every raw image here puts costly PIL copies in
                # the PGD training hot path.  Keep only the dataset-local index
                # and restore raw samples after RAER has selected the winners.
                candidate = int(source_indices[index])
            self._raer_candidates.setdefault(class_id, []).append(
                (candidate, int(difficulty[index].item()))
            )

        raw_logits = self.model(adversarial)
        calibrated = self.calibrate_logits(raw_logits)
        current_loss = F.cross_entropy(calibrated[:stream_count], labels[:stream_count])
        memory_loss = current_loss.new_zeros(())
        if labels.shape[0] > stream_count:
            memory_loss = F.cross_entropy(calibrated[stream_count:], labels[stream_count:])
        loss = current_loss + memory_loss
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()
        return {
            "loss": float(loss.detach().item()),
            "current_loss": float(current_loss.detach().item()),
            "memory_loss": float(memory_loss.detach().item()),
            "robust_difficulty": float(difficulty[:stream_count].float().mean().item()),
            "raer_acceptance": float(
                difficulty[:stream_count].lt(int(self.raer_threshold)).float().mean().item()
            ),
            "calibration_margin": self.calibration_margin(),
        }

    def train_epoch(self, dataloader: DataLoader, task_id: str) -> MetricDict:
        self.model.to(self.device).train()
        totals: Dict[str, float] = {}
        total_examples = 0
        for batch in dataloader:
            inputs = move_to_device(batch[0], self.device)
            targets = move_to_device(batch[1], self.device).long()
            source_indices = batch[2] if len(batch) > 2 else None
            metrics = self.observe(
                inputs,
                targets,
                task_id,
                source_indices=source_indices,
                source_dataset=dataloader.dataset if source_indices is not None else None,
            )
            batch_size = int(targets.shape[0])
            total_examples += batch_size
            for name, value in metrics.items():
                totals[name] = totals.get(name, 0.0) + float(value) * batch_size
        if total_examples == 0:
            return {"loss": 0.0}
        return {name: value / total_examples for name, value in totals.items()}

    def train_task(
        self,
        task: TaskDefinition,
        dataloader: DataLoader,
        epochs: int,
        epoch_callback: Callable[[MetricDict], None] | None = None,
    ) -> List[MetricDict]:
        self._refresh_class_counts(dataloader)
        self._raer_source_dataset = None
        history: List[MetricDict] = []
        for epoch in range(int(epochs)):
            # The final epoch's K values give one score per stream visit and
            # avoid repeated copies of the same sample across epochs.
            self._raer_candidates = {class_id: [] for class_id in self.new_classes}
            metrics = self.train_epoch(dataloader, task.task_id)
            metrics["epoch"] = float(epoch)
            history.append(metrics)
            if epoch_callback is not None:
                epoch_callback(metrics)
        return history

    def update_raer_memory(self) -> None:
        if int(self.memory_budget) == 0:
            self.exemplar_sets.clear()
            return
        per_class = int(self.memory_budget) // max(1, len(self.seen_classes))
        if per_class <= 0:
            raise ValueError("memory_budget must hold at least one sample per seen class.")
        for class_id in self.old_classes:
            old = list(self.exemplar_sets.get(class_id, []))
            self.exemplar_sets[class_id] = random.sample(old, min(per_class, len(old)))
        for class_id in self.new_classes:
            scored = self._raer_candidates.get(class_id, [])
            eligible: List[Exemplar | int] = [
                candidate
                for candidate, difficulty in scored
                if difficulty < int(self.raer_threshold)
            ]
            selected = random.sample(
                eligible, min(per_class, len(eligible))
            )
            exemplars: List[Exemplar] = []
            for candidate in selected:
                if isinstance(candidate, int):
                    if self._raer_source_dataset is None:
                        raise RuntimeError(
                            "RAER cannot restore indexed candidates without their dataset."
                        )
                    exemplar = _stored_exemplar(
                        self._raer_source_dataset, candidate
                    )
                else:
                    exemplar = candidate
                if int(exemplar[1]) != int(class_id):
                    raise ValueError(
                        "Stored RAER exemplar label does not match its candidate class."
                    )
                exemplars.append(exemplar)
            self.exemplar_sets[class_id] = exemplars
        for class_id in self.seen_classes:
            self.class_counts[class_id] = len(self.exemplar_sets.get(class_id, []))

    def _on_task_end(self, task: TaskDefinition, train_loader: DataLoader) -> None:
        del task, train_loader
        self.update_raer_memory()


AFLC_RAER = AFLCRAERLearner

__all__ = ["AFLC_RAER", "AFLCRAERLearner"]
